### ISSUE TITLE
ARC support

### ISSUE THREAD

**Issue by tonyarnold** [TimOliver/XADMaster#1]
Let's party like ARC didn't happen many moons ago :full_moon_with_face:

**Comment by tonyarnold** [comment]
_And then Tony looks at the source code and cries_

**Comment by TimOliver** [comment]
Hahahaha yeah. I had that brief thought too, and then looked at the code and went NOPE. XD

Ooh, this reminds me though. I need to update this repo with the code from v1.1. I did a bunch of re-factoring so it would compile a bit nicer in 64-bit iOS builds.

**Comment by tonyarnold** [comment]
@TimOliver any chance of that v1.1 update commit? _nudge, nudge_ :smile:

**Comment by TimOliver** [comment]
ROFL! Oops. Sorry. I forgot to do this.

All done now! Enjoy!

**Comment by TimOliver** [comment]
Um. I just read that title again. No ARC support sadly, but at least the 64-bit warnings are gone...

**Comment by tonyarnold** [comment]
Ta, @TimOliver — x64 support is one step closer though, so this is good :dancer:
